services:
  web:
    build: .
    container_name: triptivo
    command: gunicorn triptivo.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - media_data:/app/media
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/app/media
      - static_data:/app/static
    depends_on:
      - web

volumes:
  media_data:
  static_data: