# Generated by Django 5.2.5 on 2025-08-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='experience',
        ),
    ]
